// <auto-generated />
using Final.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Final.Migrations
{
    [DbContext(typeof(QuotesDbContext))]
    [Migration("20220418174826_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24");

            modelBuilder.Entity("Final.Models.Quote", b =>
                {
                    b.Property<int>("QuoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Citation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("QuoteID");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            QuoteID = 1,
                            Author = "Ingmar Bergman",
                            Citation = "The Internet",
                            Date = "April 4, 1946",
                            QuoteText = "No form of art goes beyond ordinary consciousness as film does, straight to our emotions, deep into the twilight room of the soul.",
                            Subject = "Film"
                        },
                        new
                        {
                            QuoteID = 2,
                            Author = "Jean-Luc Godard",
                            Citation = "The Internet",
                            Date = "June 1965",
                            QuoteText = "The cinema is not an art which films life: the cinema is something between art and life.",
                            Subject = "Film"
                        },
                        new
                        {
                            QuoteID = 3,
                            Author = "David Lynch",
                            Citation = "The Internet",
                            Date = "September 2003",
                            QuoteText = "It’s better not to know so much about what things mean or how they might be interpreted or you’ll be too afraid to let things keep happening.",
                            Subject = "Film"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
